//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteCotizaciones.ReferenciaCotizaciones {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReferenciaCotizaciones.ServicioCotizacionSoap")]
    public interface ServicioCotizacionSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fecha del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerCotizacion", ReplyAction="*")]
        ClienteCotizaciones.ReferenciaCotizaciones.obtenerCotizacionResponse obtenerCotizacion(ClienteCotizaciones.ReferenciaCotizaciones.obtenerCotizacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerCotizacion", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteCotizaciones.ReferenciaCotizaciones.obtenerCotizacionResponse> obtenerCotizacionAsync(ClienteCotizaciones.ReferenciaCotizaciones.obtenerCotizacionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fecha del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarCotizacion", ReplyAction="*")]
        ClienteCotizaciones.ReferenciaCotizaciones.registrarCotizacionResponse registrarCotizacion(ClienteCotizaciones.ReferenciaCotizaciones.registrarCotizacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarCotizacion", ReplyAction="*")]
        System.Threading.Tasks.Task<ClienteCotizaciones.ReferenciaCotizaciones.registrarCotizacionResponse> registrarCotizacionAsync(ClienteCotizaciones.ReferenciaCotizaciones.registrarCotizacionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerCotizacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerCotizacion", Namespace="http://tempuri.org/", Order=0)]
        public ClienteCotizaciones.ReferenciaCotizaciones.obtenerCotizacionRequestBody Body;
        
        public obtenerCotizacionRequest() {
        }
        
        public obtenerCotizacionRequest(ClienteCotizaciones.ReferenciaCotizaciones.obtenerCotizacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerCotizacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fecha;
        
        public obtenerCotizacionRequestBody() {
        }
        
        public obtenerCotizacionRequestBody(string fecha) {
            this.fecha = fecha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerCotizacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerCotizacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteCotizaciones.ReferenciaCotizaciones.obtenerCotizacionResponseBody Body;
        
        public obtenerCotizacionResponse() {
        }
        
        public obtenerCotizacionResponse(ClienteCotizaciones.ReferenciaCotizaciones.obtenerCotizacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerCotizacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string obtenerCotizacionResult;
        
        public obtenerCotizacionResponseBody() {
        }
        
        public obtenerCotizacionResponseBody(string obtenerCotizacionResult) {
            this.obtenerCotizacionResult = obtenerCotizacionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarCotizacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarCotizacion", Namespace="http://tempuri.org/", Order=0)]
        public ClienteCotizaciones.ReferenciaCotizaciones.registrarCotizacionRequestBody Body;
        
        public registrarCotizacionRequest() {
        }
        
        public registrarCotizacionRequest(ClienteCotizaciones.ReferenciaCotizaciones.registrarCotizacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarCotizacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fecha;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal monto;
        
        public registrarCotizacionRequestBody() {
        }
        
        public registrarCotizacionRequestBody(string fecha, decimal monto) {
            this.fecha = fecha;
            this.monto = monto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarCotizacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarCotizacionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClienteCotizaciones.ReferenciaCotizaciones.registrarCotizacionResponseBody Body;
        
        public registrarCotizacionResponse() {
        }
        
        public registrarCotizacionResponse(ClienteCotizaciones.ReferenciaCotizaciones.registrarCotizacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarCotizacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string registrarCotizacionResult;
        
        public registrarCotizacionResponseBody() {
        }
        
        public registrarCotizacionResponseBody(string registrarCotizacionResult) {
            this.registrarCotizacionResult = registrarCotizacionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioCotizacionSoapChannel : ClienteCotizaciones.ReferenciaCotizaciones.ServicioCotizacionSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioCotizacionSoapClient : System.ServiceModel.ClientBase<ClienteCotizaciones.ReferenciaCotizaciones.ServicioCotizacionSoap>, ClienteCotizaciones.ReferenciaCotizaciones.ServicioCotizacionSoap {
        
        public ServicioCotizacionSoapClient() {
        }
        
        public ServicioCotizacionSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioCotizacionSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCotizacionSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCotizacionSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteCotizaciones.ReferenciaCotizaciones.obtenerCotizacionResponse ClienteCotizaciones.ReferenciaCotizaciones.ServicioCotizacionSoap.obtenerCotizacion(ClienteCotizaciones.ReferenciaCotizaciones.obtenerCotizacionRequest request) {
            return base.Channel.obtenerCotizacion(request);
        }
        
        public string obtenerCotizacion(string fecha) {
            ClienteCotizaciones.ReferenciaCotizaciones.obtenerCotizacionRequest inValue = new ClienteCotizaciones.ReferenciaCotizaciones.obtenerCotizacionRequest();
            inValue.Body = new ClienteCotizaciones.ReferenciaCotizaciones.obtenerCotizacionRequestBody();
            inValue.Body.fecha = fecha;
            ClienteCotizaciones.ReferenciaCotizaciones.obtenerCotizacionResponse retVal = ((ClienteCotizaciones.ReferenciaCotizaciones.ServicioCotizacionSoap)(this)).obtenerCotizacion(inValue);
            return retVal.Body.obtenerCotizacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteCotizaciones.ReferenciaCotizaciones.obtenerCotizacionResponse> ClienteCotizaciones.ReferenciaCotizaciones.ServicioCotizacionSoap.obtenerCotizacionAsync(ClienteCotizaciones.ReferenciaCotizaciones.obtenerCotizacionRequest request) {
            return base.Channel.obtenerCotizacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteCotizaciones.ReferenciaCotizaciones.obtenerCotizacionResponse> obtenerCotizacionAsync(string fecha) {
            ClienteCotizaciones.ReferenciaCotizaciones.obtenerCotizacionRequest inValue = new ClienteCotizaciones.ReferenciaCotizaciones.obtenerCotizacionRequest();
            inValue.Body = new ClienteCotizaciones.ReferenciaCotizaciones.obtenerCotizacionRequestBody();
            inValue.Body.fecha = fecha;
            return ((ClienteCotizaciones.ReferenciaCotizaciones.ServicioCotizacionSoap)(this)).obtenerCotizacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteCotizaciones.ReferenciaCotizaciones.registrarCotizacionResponse ClienteCotizaciones.ReferenciaCotizaciones.ServicioCotizacionSoap.registrarCotizacion(ClienteCotizaciones.ReferenciaCotizaciones.registrarCotizacionRequest request) {
            return base.Channel.registrarCotizacion(request);
        }
        
        public string registrarCotizacion(string fecha, decimal monto) {
            ClienteCotizaciones.ReferenciaCotizaciones.registrarCotizacionRequest inValue = new ClienteCotizaciones.ReferenciaCotizaciones.registrarCotizacionRequest();
            inValue.Body = new ClienteCotizaciones.ReferenciaCotizaciones.registrarCotizacionRequestBody();
            inValue.Body.fecha = fecha;
            inValue.Body.monto = monto;
            ClienteCotizaciones.ReferenciaCotizaciones.registrarCotizacionResponse retVal = ((ClienteCotizaciones.ReferenciaCotizaciones.ServicioCotizacionSoap)(this)).registrarCotizacion(inValue);
            return retVal.Body.registrarCotizacionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteCotizaciones.ReferenciaCotizaciones.registrarCotizacionResponse> ClienteCotizaciones.ReferenciaCotizaciones.ServicioCotizacionSoap.registrarCotizacionAsync(ClienteCotizaciones.ReferenciaCotizaciones.registrarCotizacionRequest request) {
            return base.Channel.registrarCotizacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteCotizaciones.ReferenciaCotizaciones.registrarCotizacionResponse> registrarCotizacionAsync(string fecha, decimal monto) {
            ClienteCotizaciones.ReferenciaCotizaciones.registrarCotizacionRequest inValue = new ClienteCotizaciones.ReferenciaCotizaciones.registrarCotizacionRequest();
            inValue.Body = new ClienteCotizaciones.ReferenciaCotizaciones.registrarCotizacionRequestBody();
            inValue.Body.fecha = fecha;
            inValue.Body.monto = monto;
            return ((ClienteCotizaciones.ReferenciaCotizaciones.ServicioCotizacionSoap)(this)).registrarCotizacionAsync(inValue);
        }
    }
}
